"""文件功能：覆盖 AI paused run、用户反馈与继续执行链路测试。"""

from tests.integration.ai.ai_agents_pause_resume_cases import (
    test_ai_resolve_requirement_payload_should_use_latest_active_requirement,
    test_ai_run_output_with_pending_feedback_should_be_normalized_as_paused,
    test_ai_raw_continue_exception_should_mark_resolved_confirmation_error,
    test_ai_raw_sse_should_stop_and_release_lock_after_pause_event,
    test_ai_stream_should_release_session_lock_after_pause_event,
    test_apply_user_feedback_selections_should_write_preset_and_custom_answers,
    test_extract_pending_requirement_should_fallback_to_paused_tools,
    test_extract_pending_requirement_should_keep_pause_when_edits_preview_fails,
    test_extract_pending_requirement_should_support_user_feedback_questions,
    test_extract_pending_requirement_should_build_canonical_diff_from_edits,
    test_ai_continue_active_events_should_accept_pending_requirement_on_failed_agno_run,
)
