"""文件功能：覆盖 AI paused run、用户反馈与继续执行链路测试。"""

from tests.integration.ai.ai_agents_cases import (
    test_ai_paused_session_messages_should_be_visible,
    test_ai_resolve_requirement_payload_should_use_latest_active_requirement,
    test_ai_run_output_with_pending_feedback_should_be_normalized_as_paused,
    test_ai_session_active_run_should_not_restore_requirement_from_completed_task,
    test_ai_session_active_run_should_restore_feedback_requirement_from_failed_task,
    test_ai_session_active_run_should_return_paused_requirement,
    test_ai_stream_should_release_session_lock_after_pause_event,
    test_ai_startup_recovery_should_keep_interrupted_feedback_run_paused,
    test_apply_user_feedback_selections_should_write_preset_and_custom_answers,
    test_extract_pending_requirement_should_fallback_to_paused_tools,
    test_extract_pending_requirement_should_keep_pause_when_edits_preview_fails,
    test_extract_pending_requirement_should_support_user_feedback_questions,
    test_extract_pending_requirement_should_build_canonical_diff_from_edits,
    test_ai_continue_active_events_should_accept_pending_requirement_on_failed_agno_run,
    test_ai_completed_confirmed_route_tool_should_cleanup_agno_hitl,
    test_continue_non_paused_run_should_not_reset_tool_auth,
    test_replayed_pause_event_after_continue_should_not_disable_tool_auth,
    test_tool_auth_should_reset_window_when_paused_run_continues,
)
