"""add asset_type and tags to workspace_assets

Revision ID: d8604be26ae5
Revises: da0e6af4a1a6
Create Date: 2026-04-11 13:50:17.275625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8604be26ae5'
down_revision: Union[str, Sequence[str], None] = 'da0e6af4a1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_assets', sa.Column('asset_type', sa.String(length=50), server_default='icon', nullable=False))
    op.add_column('workspace_assets', sa.Column('tags', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_assets', 'tags')
    op.drop_column('workspace_assets', 'asset_type')
    # ### end Alembic commands ###
